### ISSUE TITLE
Use of markdig.signed?

### ISSUE THREAD

**Issue by seb-giroux** [Kryptos-FR/markdig.wpf#19]
Hi,

Do you intend on releasing a version that uses markdig.signed instead of markdig?

**Comment by khdc** [comment]
I definitely need a signed version for my application too.

**Comment by mengluwang121** [comment]
Hi,

This is still Menglu from VisualStudio setup team... We are considering using this package in a .Net 4.5 project for Markdown support. But we definitely need to use the signed version which has a strong name. We would really appreciate it if we can get help from you to update a signed version of nuget package! Thank you so very much!

Best,
Menglu

**Comment by Kryptos-FR** [comment]
I still don't see the point of signed assemblies in 2019. It supposedly solves an issue that doesn't exist anymore.

I can find as many pros and cons as I want in serious websites/blogs.

That said, since it seems to be a required feature for some of you, I'll have a look at it in the following week. I'm quite busy right now but I'll be on leave next week.

**Comment by mengluwang121** [comment]
Hi,

Thank you so much for the quick response Kryptos. We really appreciate your understand and help!
Please let us know if there is any further question, information or help that needed. :)

To provide more background about the reason why we still need it:
1. Microsoft policy requires we use strong name for every repo. Unfortunately a Strong-Named Assembly requires every assmeblies it relies on to be Strong-Named :( 
2. We understand this is not for security reason, but it is actually benefit for avoiding name collision. With that said, checking in a snk file to your repo probably be good enough(since it is not for security anyway).
Also, here is a MS documentation about strong-name-signing: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

Again, really appreciate your help!

Best,
Menglu

**Comment by Kryptos-FR** [comment]
Package published: https://www.nuget.org/packages/Markdig.Wpf.Signed/

Tell me if this works out for you.

**Comment by mengluwang121** [comment]
Thank you so much!!! It works great~! May you have a wonderful day!
