### ISSUE TITLE
Update to Markdig 0.21.1

### ISSUE THREAD

**Issue by amkuchta** [Kryptos-FR/markdig.wpf#42]
Currently,  I am unable to update to the latest version of Markdig (0.21.1), as it is deemed to be incompatible with the latest release of Markdig.Wpf (0.3.1)

**Comment by Kryptos-FR** [comment]
I have to use an exact version each release because of #20 (related to https://github.com/lunet-io/markdig/issues/274).

And now, on top of that, Markdig have decided do drop support for .NET Framework 4.0 which was requested by another user (#25) and is currently being discussed in #41.

**Comment by Kryptos-FR** [comment]
Despite #20, I will relax the dependency rule. It might break sometimes, but at least it won't prevent to upgrade to a later version when it still works.

_edit:_ rule relaxed in version **0.4.0**. I was able to upgrade up to **Markdig 0.20.0**, however **0.21.0** breaks with some `MissingMethodException` so it will need some updates before you can use it. I plan to do so in the next version.

**Comment by tjdennis** [comment]
Hi. Is there any update coming to this project that fixes the MissingMethodException?  Markdig is now at 0.22.0 and I would love to be able to use your project for displaying markdown files instead of bouncing them through HTML.  I am seeing the error with Markdig 0.20.0 as well.  

The missing method "Write" is there and hasn't changed. Maybe you're missing some new interface method or it's a difference in your Render signature that's causing the underlying RenderBase class from instantiating.  You have a [NotNull] in yours.

Thanks!

**Comment by Kryptos-FR** [comment]
Hi @tjdennis. What are you taking about?

**Comment by Kryptos-FR** [comment]
@tjdennis I pushed version `0.5.0`. Can you tell me if it works for you?

**Comment by Mertsch** [comment]
For me Markdig.Wpf 0.5.0 works great with Markdig 0.22 and 0.22.1

**Comment by Kryptos-FR** [comment]
@Mertsch thanks for confirming. I'll keep this issue open until #43 is resolved.

**Comment by Kryptos-FR** [comment]
Closing as #43 is now resolved.
