### ISSUE TITLE
Markdig.Wpf 0.5.0 requires Markdig.Signed on assembly level (package states Markdig)

### ISSUE THREAD

**Issue by Mertsch** [Kryptos-FR/markdig.wpf#43]
I think the `Markdig.Wpf.dll` not completely isolated from the "Signed" build.
Quickly scanning the file with a text editor reveals a `Markdig.Signed` string present in the unsigned `dll`.

As a workaround I am now using the `Markdig.Wpf.Signed`, which correctly works.

**Comment by Kryptos-FR** [comment]
Hmm. I might have messed up something during the build. I'll try to fix it. Thanks for notifying.

Edit: I have contacted NuGet support to ask them to remove the package so I can upload it again. It is usually against their policy to re-upload an existing package. At least they don't let you do it by yourself.

Depending on what is decided, it will either be fixed or I will upload a new version and ask to de-list 0.5.0 so that people don't encounter the issue.

**Comment by Kryptos-FR** [comment]
@Mertsch I have uploaded a new version `0.5.0.1`.

**Comment by Mertsch** [comment]
Works 😊
