### ISSUE TITLE
I need to replace CodeBlockRenderer as AvalonEdit TextEditor

### ISSUE THREAD

**Issue by ebattulga** [Kryptos-FR/markdig.wpf#58]
How i can implement AvalonEdit TextEditor as CodeBlockRenderer? I didn't find any accessor from MarkdownViewer. please help me

**Comment by Kryptos-FR** [comment]
Editing is not something that is currently supported. The purpose of this library is to render the markdown.

PR welcome to add the feature.

My guess on how to do it is there could be flag setting somewhere and during the "rendering" phase, inject AvalonEdit instead of the current code block.

Or it could be another approach using styles and control templates.
