### ISSUE TITLE
Target .Net 4.5.0 instead of .Net 4.5.2

### ISSUE THREAD

**Issue by Logikgate** [Kryptos-FR/markdig.wpf#8]
Hello,

Awesome repo it makes using Markdown in a WPF form a breeze.  Would you accept a pull request to have markdig.wpf target .net framework 4.5.0 instead of 4.5.2? The Markdig project itself targets 4.5.0 and targeting version 4.5.2 really limits the number of machines this can be used on without first ensuring the framework is installed.  Windows 10 was the first release that shipped with support for v4.5.2 and above so for any machine running Windows 8 and lower we can't assume that v4.5.2 will exist.

**Comment by Kryptos-FR** [comment]
4.5.0 and 4.5.1 have been deprecated since January 12, 2016. Microsoft doesn't provide any support for those versions anymore (not even security updates). Any up-to-date system already supports 4.5.2. That includes all version of Windows currently supported by Microsoft, i.e. Windows 7, 8.1 (and 10 since 4.6+ is installed on it).

> .NET Framework 4.5.2: Support for .NET 4.5.2 follows the lifecycle policy of the parent operating system. It is supported as a Windows component on the latest required operating system update for Windows Vista SP2, Windows 7 SP1, Windows Server 2008 SP2, Windows Server 2008 R2 SP1, Windows 8.1 Update, Windows Server 2012, and Windows Server 2012 R2.

Reference: https://support.microsoft.com/en-us/help/17455/lifecycle-faq-net-framework

The only machines that might have issues are those that have not been updated since January 2016. Those machines are vulnerable to attacks. I believe it is a good practice to encourage people to always keep their system up-to-date. For that reason I don't want to target an obsolete framework.

Since this project is MIT you can always modify the target yourself and recompile to match your needs. But otherwise I have to decline your request.
